"""Juror construction — two modes.

scripted : a fixed cast of 5 hand-written personas (deterministic, demo-stable).
dynamic  : personas generated by the LLM from the case (generate_jurors).
A human juror (`is_human=True`) is always appended.
"""
from __future__ import annotations

from .cases import Case
from .state import HUMAN_ID, JurorState, Persona, Vote

# Fixed initial scores keep the speaking order deterministic for demos.
_SCRIPTED = [
    Persona("j1", "Marian Vasquez", "retired structural engineer who trusts physical proof",
            "anchors hard on forensic evidence and distrusts witnesses", "GUILTY",
            "precise, measured, fond of 'the numbers don't lie'"),
    Persona("j2", "Dewey Park", "small-business owner, impatient to get home",
            "wants to wrap up fast and leans with the majority", "GUILTY",
            "blunt, folksy, a little dismissive"),
    Persona("j3", "Aisha Bello", "public defender's paralegal, fixated on reasonable doubt",
            "skeptical of the prosecution; magnifies any gap in proof", "NOT_GUILTY",
            "calm, rigorous, asks pointed questions"),
    Persona("j4", "Tom Halloran", "ex-cop who respects informants and priors",
            "credits law enforcement and criminal history heavily", "GUILTY",
            "gruff, certain, street-smart"),
    Persona("j5", "Priya Nair", "schoolteacher who weighs both sides emotionally",
            "swings with the most recent compelling story (recency bias)", "UNDECIDED",
            "warm, empathetic, thinks out loud"),
]

_SCORES = {  # (speaking, responding)
    "j1": (0.80, 0.40), "j2": (0.55, 0.70), "j3": (0.75, 0.55),
    "j4": (0.70, 0.45), "j5": (0.50, 0.65),
}


def _human() -> JurorState:
    persona = Persona(HUMAN_ID, "You", "the human juror", "your own judgment",
                      "UNDECIDED", "your own voice")
    return JurorState(persona=persona, vote="UNDECIDED",
                      speaking_score=0.0, responding_score=0.0, is_human=True)


def scripted_jurors(case: Case) -> tuple[JurorState, ...]:
    ai = tuple(
        JurorState(persona=p, vote=p.initial_leaning,
                   speaking_score=_SCORES[p.id][0], responding_score=_SCORES[p.id][1])
        for p in _SCRIPTED
    )
    return ai + (_human(),)


def dynamic_jurors(case: Case, llm, n: int = 5) -> tuple[JurorState, ...]:
    """Generate personas via the LLM; fall back to scripted on failure/empty."""
    raw = llm.generate_personas(case, n)
    if not raw:
        return scripted_jurors(case)
    ai = []
    for i, r in enumerate(raw, start=1):
        leaning: Vote = (r.get("initial_leaning") or "UNDECIDED").upper().replace("-", "_")
        if leaning not in ("GUILTY", "NOT_GUILTY", "UNDECIDED"):
            leaning = "UNDECIDED"
        p = Persona(
            id=f"j{i}", name=r.get("name", f"Juror {i}"),
            archetype=r.get("archetype", "a juror"), bias=r.get("bias", "no strong bias"),
            initial_leaning=leaning, voice=r.get("voice", "plain spoken"),
        )
        ai.append(JurorState(persona=p, vote=leaning,
                             speaking_score=0.5 + 0.05 * i, responding_score=0.5))
    return tuple(ai) + (_human(),)


def build_jurors(case: Case, mode: str, llm=None) -> tuple[JurorState, ...]:
    if mode == "dynamic" and llm is not None:
        return dynamic_jurors(case, llm)
    return scripted_jurors(case)
