"""Juror construction — two modes, bilingual personas.

scripted : a fixed cast of 5 hand-written personas (deterministic, demo-stable).
dynamic  : personas generated by the LLM from the case (generate_jurors).
A human juror (`is_human=True`) is always appended. `lang` selects en/zh persona
text (names are kept as proper nouns in both).
"""
from __future__ import annotations

from .cases import Case
from .state import HUMAN_ID, JurorState, Persona, Vote

# (id, name, archetype, bias, leaning, voice)
_SCRIPTED_EN = [
    ("j1", "Marian Vasquez", "retired structural engineer who trusts physical proof",
     "anchors hard on forensic evidence and distrusts witnesses", "GUILTY",
     "precise, measured, fond of 'the numbers don't lie'"),
    ("j2", "Dewey Park", "small-business owner, impatient to get home",
     "wants to wrap up fast and leans with the majority", "GUILTY",
     "blunt, folksy, a little dismissive"),
    ("j3", "Aisha Bello", "public defender's paralegal, fixated on reasonable doubt",
     "skeptical of the prosecution; magnifies any gap in proof", "NOT_GUILTY",
     "calm, rigorous, asks pointed questions"),
    ("j4", "Tom Halloran", "ex-cop who respects informants and priors",
     "credits law enforcement and criminal history heavily", "GUILTY",
     "gruff, certain, street-smart"),
    ("j5", "Priya Nair", "schoolteacher who weighs both sides emotionally",
     "swings with the most recent compelling story (recency bias)", "UNDECIDED",
     "warm, empathetic, thinks out loud"),
]

_SCRIPTED_ZH = [
    ("j1", "Marian Vasquez", "信赖物证的退休结构工程师",
     "强烈依赖法医/物证，不信任证人证词", "GUILTY",
     "精确、克制，爱说『数字不会撒谎』"),
    ("j2", "Dewey Park", "急着回家的小店主",
     "想尽快了结，倾向于随大流", "GUILTY",
     "直接、接地气，略带轻慢"),
    ("j3", "Aisha Bello", "公设辩护人的律师助理，执着于合理怀疑",
     "对控方持怀疑态度，放大证明中的任何漏洞", "NOT_GUILTY",
     "冷静、严谨，爱发尖锐问题"),
    ("j4", "Tom Halloran", "尊重线人与前科的前警察",
     "高度采信执法机关与犯罪历史", "GUILTY",
     "粗粝、笃定、街头智慧"),
    ("j5", "Priya Nair", "感性地权衡两边的中学教师",
     "被最近一个有说服力的说法带着走（近因偏见）", "UNDECIDED",
     "温暖、共情、边想边说"),
]

_SCORES = {  # (speaking, responding) — fixed for deterministic demo order
    "j1": (0.80, 0.40), "j2": (0.55, 0.70), "j3": (0.75, 0.55),
    "j4": (0.70, 0.45), "j5": (0.50, 0.65),
}

_HUMAN = {
    "en": ("You", "the human juror", "your own judgment", "your own voice"),
    "zh": ("你", "人类陪审员", "你自己的判断", "你自己的声音"),
}


def _human(lang: str) -> JurorState:
    name, archetype, bias, voice = _HUMAN[lang if lang in _HUMAN else "en"]
    persona = Persona(HUMAN_ID, name, archetype, bias, "UNDECIDED", voice)
    return JurorState(persona=persona, vote="UNDECIDED",
                      speaking_score=0.0, responding_score=0.0, is_human=True)


def scripted_jurors(case: Case, lang: str = "en") -> tuple[JurorState, ...]:
    rows = _SCRIPTED_ZH if lang == "zh" else _SCRIPTED_EN
    ai = tuple(
        JurorState(
            persona=Persona(pid, name, archetype, bias, leaning, voice),  # type: ignore[arg-type]
            vote=leaning,  # type: ignore[arg-type]
            speaking_score=_SCORES[pid][0], responding_score=_SCORES[pid][1])
        for (pid, name, archetype, bias, leaning, voice) in rows
    )
    return ai + (_human(lang),)


def dynamic_jurors(case: Case, llm, lang: str = "en", n: int = 5) -> tuple[JurorState, ...]:
    """Generate personas via the LLM; fall back to scripted on failure/empty."""
    raw = llm.generate_personas(case, n)
    if not raw:
        return scripted_jurors(case, lang)
    ai = []
    for i, r in enumerate(raw, start=1):
        leaning: Vote = (r.get("initial_leaning") or "UNDECIDED").upper().replace("-", "_")
        if leaning not in ("GUILTY", "NOT_GUILTY", "UNDECIDED"):
            leaning = "UNDECIDED"
        p = Persona(
            id=f"j{i}", name=r.get("name", f"Juror {i}"),
            archetype=r.get("archetype", "a juror"), bias=r.get("bias", "no strong bias"),
            initial_leaning=leaning, voice=r.get("voice", "plain spoken"),
        )
        ai.append(JurorState(persona=p, vote=leaning,
                             speaking_score=0.5 + 0.05 * i, responding_score=0.5))
    return tuple(ai) + (_human(lang),)


def build_jurors(case: Case, mode: str, llm=None, lang: str = "en") -> tuple[JurorState, ...]:
    if mode == "dynamic" and llm is not None:
        return dynamic_jurors(case, llm, lang)
    return scripted_jurors(case, lang)
