"""Offline deterministic LLM stub (no network, no API key).

Enabled via JURY_FAKE_LLM=1 — lets the full HTTP + SSE + engine pipeline run for
CI / boot-smoke / offline demos when a Gemini key isn't available. Duck-types
JuryLLM. RAG still runs for real over a local embedder so tool_call / tool_result
events fire exactly as in live mode.

NOTE: this is a placeholder. With a real GEMINI_API_KEY each juror's statement is
uniquely generated by Gemini; here we hand-write one persona-flavored line each so
the offline demo still looks like a varied deliberation rather than 5 identical lines.
"""
from __future__ import annotations

import re

import numpy as np

_VOTE_ZH = {"GUILTY": "有罪", "NOT_GUILTY": "无罪", "UNDECIDED": "未决"}

# CJK chars are tokenized individually (Chinese has no spaces); latin words and
# digit runs as whole tokens. Without the CJK class, Chinese text yields ZERO
# tokens → zero vectors → meaningless retrieval.
_TOKEN_RE = re.compile(r"[a-z]+|[0-9]+|[一-鿿]")


def offline_embed(text: str, dim: int = 512):
    v = np.zeros(dim)
    for tok in _TOKEN_RE.findall(text.lower()):
        v[hash(tok) % dim] += 1.0
    return v


# Persona-differentiated lines so the offline demo reads like a real argument.
# key = juror id; each cites a DIFFERENT angle/evidence so retrieval differs too.
_LINES = {
    "j1": {  # forensic, leans guilty
        "q_zh": "指纹 匹配 9 点 标准", "q_en": "fingerprint 9 point match standard",
        "say_zh": "指纹虽只有 9 个特征点、低于 12 点标准，但确与被告一致，物证不会说谎——我倾向有罪。",
        "say_en": "The print is only a 9-point match, below the 12-point bar, but it's consistent with the defendant — physical proof doesn't lie. I lean guilty.",
        "reb_zh": "我不否认证据有缺口，但忽视一枚一致的指纹同样是不负责任的。",
        "reb_en": "I won't deny the gaps, but ignoring a consistent print is just as careless.",
    },
    "j2": {  # impatient, leans guilty
        "q_zh": "线人 监控 身高", "q_en": "informant CCTV height",
        "say_zh": "线人听到他吹嘘『Marlin 那票』，监控身高也对得上，证据够多了，别拖——有罪。",
        "say_en": "The informant heard him brag about 'the Marlin job' and the CCTV height fits. That's enough — guilty.",
        "reb_zh": "你们越分析越复杂，普通人看这些证据早就有结论了。",
        "reb_en": "The more you slice it the messier it gets — any reasonable person already sees it.",
    },
    "j3": {  # reasonable doubt, leans not guilty
        "q_zh": "不在场证明 外卖 收据 手机基站", "q_en": "alibi delivery receipt phone tower",
        "say_zh": "外卖收据和手机基站都把他放在 4 英里外的女友家，这本身就是合理怀疑——无罪。",
        "say_en": "The delivery receipt and phone tower both place him 4 miles away at his girlfriend's — that's reasonable doubt. Not guilty.",
        "reb_zh": "控方连撬棍和赃物都拿不出，怎么能说『排除合理怀疑』？",
        "reb_en": "The prosecution has no crowbar and no stolen goods — how is that beyond a reasonable doubt?",
    },
    "j4": {  # ex-cop, leans guilty
        "q_zh": "前科 线人 可信度", "q_en": "prior conviction informant credibility",
        "say_zh": "他有前科、又有同囚线人指证，执法不会无的放矢，我认为有罪。",
        "say_en": "He has a prior and a cellmate informant against him — police don't act on nothing. Guilty in my book.",
        "reb_zh": "线人换减刑没错，但这不代表他在撒谎。",
        "reb_en": "Sure the informant got a deal — that doesn't mean he's lying.",
    },
    "j5": {  # emotional, undecided
        "q_zh": "手套 纤维 赃物 撬棍", "q_en": "glove fibers stolen goods crowbar",
        "say_zh": "现场有手套纤维就可能不留指纹，又始终没找到赃物或撬棍，两边都有道理，我还拿不定。",
        "say_en": "Glove fibers mean maybe no prints, and no stolen goods or crowbar ever turned up — both sides have a point. I'm undecided.",
        "reb_zh": "我听你这么说又有点动摇了，这正是我纠结的地方。",
        "reb_en": "Hearing you say that sways me again — that's exactly my struggle.",
    },
}

_DEFAULT = {
    "q_zh": "案件 证据", "q_en": "case evidence",
    "say_zh": "综合现有证据，我谈谈我的看法。", "say_en": "Weighing the evidence, here's where I stand.",
    "reb_zh": "我对此有不同看法。", "reb_en": "I see that differently.",
}


class StubLLM:
    def __init__(self, retriever, lang: str = "en"):
        self.retriever = retriever
        self.lang = lang
        self.errors: list[dict] = []

    @property
    def _zh(self) -> bool:
        return self.lang == "zh"

    def _lines(self, juror):
        return _LINES.get(juror.persona.id, _DEFAULT)

    def think(self, juror, state, case):
        n, a = juror.persona.name, juror.persona.archetype
        return f"{n}（{a}）正在掂量手头的证据。" if self._zh else f"{n} ({a}) weighs the evidence at hand."

    def speak(self, juror, state, case, on_tool_call, on_tool_result):
        L = self._lines(juror)
        on_tool_call(L["q_zh"] if self._zh else L["q_en"])
        on_tool_result(self.retriever.lookup(f'{L["q_zh"]} {L["q_en"]}', k=2))
        return (L["say_zh"] if self._zh else L["say_en"]), juror.vote

    def respond(self, juror, state, case, target_name, target_text,
                on_tool_call, on_tool_result):
        L = self._lines(juror)
        on_tool_call(L["q_zh"] if self._zh else L["q_en"])
        on_tool_result(self.retriever.lookup(f'{L["q_zh"]} {L["q_en"]}', k=1))
        if self._zh:
            return f"（回应 {target_name}）{L['reb_zh']}", juror.vote
        return f"(to {target_name}) {L['reb_en']}", juror.vote

    def revote(self, juror, state, case):
        return juror.vote, ("维持原立场" if self._zh else "holding my position")

    def hint(self, state, case):
        return ("抓住 9 点指纹匹配与实验室 12 点标准之间的差距。" if self._zh
                else "Press the gap between the 9-point print match and the lab's 12-point standard.")

    def generate_personas(self, case, n):
        return []

    def judge(self, statement, case):
        # Deterministic offline score: statements that cite concrete figures
        # (e.g. "9 point", "12-point", "4 miles") read as more evidence-grounded.
        q = 0.6 + (0.2 if any(c.isdigit() for c in statement) else 0.0)
        return {"quality": round(min(q, 0.9), 3), "fallacy": "none"}

    def rubric(self, case, human_lines, state):
        dims = {k: 72 for k in
                ["persuasiveness", "evidence_use", "consistency",
                 "engagement", "open_mindedness"]}
        recap = "离线演示评议已完成。" if self._zh else "Offline demo deliberation completed."
        return {"dims": dims, "total": 72, "recap": recap}

    def drain_errors(self):
        errs, self.errors = self.errors, []
        return errs
